apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: "{{repoURL}}"
        targetRevision: HEAD
        path: "services/{{appName}}"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - values.yaml
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  generators:
  - list:
      elements:
      - appName: app1
        namespace: default
        repoURL: https://github.com/mohankarki54/helm-demo.git
      - appName: app2
        namespace: default
        repoURL: https://github.com/mohankarki54/helm-demo.git
      - appName: app3
        namespace: default
        repoURL: https://github.com/mohankarki54/helm-demo.git