appName: mywebapp-prod
replicas: 1

service:
  ports:
    port1: 80
    protocol1: TCP
  type: LoadBalancer

configmap:
  name: myconfig-prod
  data:
    CUSTOM_HEADER: "This is deployed with helm"

image:
  name: stacksimplify/kube-nginxapp1
  tag: 1.0.0

resources:
  requests:
    memory: "20Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"   
