apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giving-partner
  namespace: argocd
spec:
  project: default
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: services/app1
    repoURL: 'https://github.com/mohankarki54/helm-demo.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - Validate=true
