appName: service-a
replicas: 1
namespace: qa-systems-engineering

service:
  ports:
    port1: 80
    protocol1: TCP
  type: LoadBalancer

image:
  name: nginx
  pullPolicy: IfNotPresent
  tag: 1.0.0

resources:
  requests:
    memory: "0.5Gi"
    cpu: "0.5"
  limits:
    memory: "0.5Gi"
    cpu: "0.5"
