apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-b
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: service-b
spec:
  project: qa-systems-engineering
  sources:
  - repoURL: 'https://raw.githubusercontent.com/mohankarki54/helm-repo/main/'
    chart: services
    targetRevision: 2.0.0
    helm:
      valueFiles:
      - $values/service-b/values-qa.yaml
  - repoURL: 'https://github.com/mohankarki54/helm-demo.git'
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: qa-systems-engineering
