appName: service-b
replicas: 1
namespace: qa-systems-engineering

service:
  ports:
    port1: 80
    protocol1: TCP
  type: LoadBalancer

image:
  name: nginx
  pullPolicy: IfNotPresent
  tag: latest

resources:
  requests:
    memory: "5Mi"
    cpu: "0.5G"
  limits:
    memory: "5Mi"
    cpu: "0.5G"
